name: digital_bank

packages:
  - app/**
  - features/**
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  postbootstrap: melos gen-l10n

  analyze:
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.
    run: |
      melos exec -c 1 -- \
        dart analyze . --fatal-infos

  format:
    description: |
      Build a specific example app for Android.
       - Requires `flutter_plugin_tools` (`dart pub global activate flutter_plugin_tools`).
       - Requires `clang-format` (can be installed via Brew on macOS).
       - Requires `swiftformat` (can be installed via Brew on macOS).
    run: |
      dart pub global run flutter_plugin_tools format && \
      swiftformat .

  lint:all:
    description: Run all static analysis checks.
    run: melos run analyze && melos run format

  test:
    description: Run `flutter test` for a specific package.
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test"
    select-package:
      dir-exists:
        - test
      ignore:
        - '*web*'
        - '*odm*'
        - '*example*'

  gen-l10n:
    description: Generate localizations
    run: |
      melos exec -c 1 --fail-fast --file-exists="l10n.yaml" -- \
        "flutter gen-l10n"

  run:ios:
    description: Run `flutter run ios` on the app.
    run: |
      melos exec -c 1 -- \
        "flutter run -t lib/main.dart ios"
    select-package:
      dir-exists:
        - "ios"

  run:android:
    description: Run `flutter run android` on the app.
    run: |
      melos exec -c 1 -- \
        "flutter run -t lib/main.dart android"
    select-package:
      dir-exists:
        - "android"
