name: data_access
description: A single source of truth for all application data.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  meta: ^1.8.0

  # Internal packages
  configs:
    path: ../configs

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
