name: data_access
description: A single source of truth for all application data.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  # Internal packages
  configs:
  # Annotations
  meta: ^1.8.0
  # Networking
  http: ^0.13.5
  # Value equality
  equatable: ^2.0.5
  # Encryption
  pointycastle: ^3.6.2
  # Conversion Utilities
  convert: ^3.1.1
  # Dependency injection
  flutter_riverpod: ^2.1.3
  # Testing
  mockito: ^5.3.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2
  # Mockito code generation
  build_runner: ^2.3.3
