name: localization
description: A custom abstraction for localizing values such as text and layouts for multiple languages.
version: 1.0.0

publish_to: 'none'

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Localizations
  flutter_localizations:
    sdk: flutter
  intl: any
  # Read environment variables from .env file
  flutter_dotenv: ^5.0.2
  # Annotations
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2

flutter:
  generate: true
