name: digital_bank
description: Proof of concept of a digital bank onboarding experience.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  # Internal packages
  configs:
  data_access:
  ds_components:

  # Features
  welcome:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: gowun_dodum
      fonts:
        - asset: assets/fonts/GowunDodum-Regular.ttf
          weight: 400

    - family: gowun_batang
      fonts:
        - asset: assets/fonts/GowunBatang-Regular.ttf
          weight: 400
        - asset: assets/fonts/GowunBatang-Bold.ttf
          weight: 500
