name: test_helper
description: A tailor-made abstraction for testing the app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  # Internal packages
  localization: any
  ds_components: any
  # State management
  flutter_riverpod: ^2.1.3
  # Testing
  mockito: ^5.3.2


dev_dependencies:
  # Linting
  flutter_lints: ^2.0.1

flutter:
