name: welcome
description: Welcome page for the digital bank app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  # Internal packages
  ds_components: any
  # Localizations
  localization: any
  # Navigation
  go_router: ^6.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Linting
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
