name: account_application
description: Account application feature for the digital bank app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  # Internal packages
  data_access: any
  ds_components: any
  localization: any
  # Value equality
  equatable: ^2.0.5
  # State management
  flutter_riverpod: ^2.1.3
  # Formatting
  intl: ^0.17.0
  # Navigation
  go_router: ^6.0.6
  # Testing
  mockito: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  test_helper: any
  # Linting
  flutter_lints: ^2.0.1
  # Mockito code generation
  build_runner: ^2.3.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/