// Mocks generated by Mockito 5.3.2 from annotations
// in data_access/test/repository/account_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:data_access/src/model/account_application.dart' as _i5;
import 'package:data_access/src/model/account_application_feedback.dart' as _i2;
import 'package:data_access/src/service/api_client/flow_bank_api_client_service.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAccountApplicationFeedback_0 extends _i1.SmartFake
    implements _i2.AccountApplicationFeedback {
  _FakeAccountApplicationFeedback_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FlowBankApiClientServiceProtocol].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockFlowBankApiClientServiceProtocol extends _i1.Mock
    implements _i3.FlowBankApiClientServiceProtocol {
  @override
  _i4.Future<_i2.AccountApplicationFeedback> createAccount(
          _i5.AccountApplication? accountApplication) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccount,
          [accountApplication],
        ),
        returnValue: _i4.Future<_i2.AccountApplicationFeedback>.value(
            _FakeAccountApplicationFeedback_0(
          this,
          Invocation.method(
            #createAccount,
            [accountApplication],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AccountApplicationFeedback>.value(
                _FakeAccountApplicationFeedback_0(
          this,
          Invocation.method(
            #createAccount,
            [accountApplication],
          ),
        )),
      ) as _i4.Future<_i2.AccountApplicationFeedback>);
}
