name: camera
description: A wrapper for accessing the device's camera.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  # Camera
  camerawesome: ^1.2.1
  path_provider: ^2.0.12
  # Open media file
  better_open_file: ^3.6.4

  # Internal packages
  ds_components:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
